apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: webderver-deployment
  namespace: default
  labels:
    app: webserver-pods
spec:
  selector:
    matchLabels:
      app: webserver-pods
  replicas: 2
  template: 
    metadata:
      labels:
        app: webserver-pods
      annotations: {
        collectord.io/volume.1-logs-name: "logs",
        collectord.io/volume.1-logs-timestampfield: "timestamp"
      }          
    spec:
      containers:
      - name: webserver-container
        image: raj11646/webserver
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: webserver-pods
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000